import type { Metadata } from 'next'
import Header from '../_components/Header'
import { EventProvider } from './contexts/EventContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <EventProvider>
    <Header>{children}</Header>
    </EventProvider>
}
