export enum OrderType {
    CHICKEN_NUGGETS = 'CHICKEN_NUGGETS',
    FRENCH_FRIES = 'FRENCH_FRIES',
    MINI_BURGER_BEEF = 'MINI_BURGER_BEEF',
    KEBBE = 'KEBBE',
    PASTA_RED_OR_WHITE = 'PASTA_RED_OR_WHITE',
    QUINOA_SALAD = 'QUINOA_SALAD',
    PASTA_SALAD = 'PASTA_SALAD',
    GREEK_SALAD = 'GREEK_SALAD',
    CHICKEN_CEASER = 'CHICKEN_CEASER',
    SALAD = 'SALAD',
    FINGER_BITES_CRAB = 'FINGER_BITES_CRAB',
    FINGER_BITES_SALMON = 'FINGER_BITES_SALMON',
    FINGER_BITES_ROAST_BEEF = 'FINGER_BITES_ROAST_BEEF',
    FINGER_BITES_HOTDOG = 'FINGER_BITES_HOTDOG',
    FINGER_BITES_CHICKEN = 'FINGER_BITES_CHICKEN',
    FINGER_BITES_TUNA = 'FINGER_BITES_TUNA',
    FINGER_BITES_CHEESE = 'FINGER_BITES_CHEESE',
    FINGER_BITES_HAM = 'FINGER_BITES_HAM',
    MI_SANDWICH_CHEESE_OR_TURKEY = 'MI_SANDWICH_CHEESE_OR_TURKEY',
    MINI_SANDWICH_CHEESE = 'MINI_SANDWICH_CHEESE',
    MINI_SANDWICH_HOTDOG = 'MINI_SANDWICH_HOTDOG',
    MINI_FAHITA_CHICKEN = 'MINI_FAHITA_CHICKEN',
    FINGER_BITES_HAM_2 = 'FINGER_BITES_HAM_2',
    M_CROISSANT_CHOCO = 'M_CROISSANT_CHOCO',
    M_CROISSANT_CHEESE = 'M_CROISSANT_CHEESE',
    M_CROISSANT_ZAATAR = 'M_CROISSANT_ZAATAR',
    MINI_PIZZA = 'MINI_PIZZA',
    MINI_ZAATAR = 'MINI_ZAATAR',
    MINI_HOTDOG = 'MINI_HOTDOG',
    MINI_SPINACH = 'MINI_SPINACH',
    MINI_SWEETS_ECLAIR = 'MINI_SWEETS_ECLAIR',
    MINI_SWEETS_TARTE = 'MINI_SWEETS_TARTE',
    MINI_SWEETS = 'MINI_SWEETS',
    DONUTS = 'DONUTS',
    POPCORN = 'POPCORN',
    JELLO_SHOTS = 'JELLO_SHOTS',
    PUDDING_CHOCO = 'PUDDING_CHOCO',
    PUDDING_VANILLA = 'PUDDING_VANILLA',
    FRUIT_SALAD = 'FRUIT_SALAD',
    MUFFINS = 'MUFFINS',
    CUPCAKE_THEMED = 'CUPCAKE_THEMED',
    COOKIES_AND_MUFFINS = 'COOKIES_AND_MUFFINS',
    LAZY_CAKE = 'LAZY_CAKE',
    NUTELLA_CREPE = 'NUTELLA_CREPE'
}

export enum UnitType {
    KG = 'KG',
    DZ = 'DZ',
    UN = 'UN'
}

export interface Order {
    id?: number
    unit: UnitType
    description: OrderType
    unitPrice: number
    quantity: number
    event?: Event
    eventId?: number
}